### ISSUE TITLE
New release 1.4.6.Final is ready.

### ISSUE THREAD

**Issue by slavap** [jqm4gwt/jqm4gwt#100]
We are ready to release a new version 1.4.6.Final
Sam, could you please fetch current master, build and deploy it to maven central.
I will update examples on appspot tomorrow.

**Comment by sksamuel** [comment]
Away on business atm, will get to this on my return this weekend.

**Comment by slavap** [comment]
Ok, thanks. If some unexpected bug occurs I will have time to fix it :-)

**Comment by sksamuel** [comment]
Released.
