### ISSUE TITLE
Memory leak fixes

### ISSUE THREAD

**Issue by roman-e** [jqm4gwt/jqm4gwt#101]
Hi

I'm developing with jqm4gwt and found some memory leaks I'd like to share with you.
- JQMControlGroup, JQMWidget, JQMColumnToggle
 - filterableCreated event won't get removed. Call off('filterablecreated') in unload method()

- JQMPage
 - remove the resizeHandler on Page unload which is set in initWindowResize() . Use a HandlerRegistration for that. 
 - Remove an unload Page from the allPages field or else it will remain in memory until the user leaves the website

Kind regards
Roman

**Comment by slavap** [comment]
Thanks! I will fix it.
