### ISSUE TITLE
JS and CSS injection needs to be configurable

### ISSUE THREAD

**Issue by esyrett** [jqm4gwt/jqm4gwt#102]
In Resources.java, we have the following code:
```Java
 private static final String JQM_FIXES_CSS = "css/jqm-fixes.css";
 private static final String JQM4GWT_CSS = "css/jqm4gwt.css";
 private static final String JQUERY_ACTUAL = "js/jquery.actual.min.js";
 private static final String JQM_FIXES_JS = "js/jqm-fixes.js";
```

These are giving us a problem when in use with Super Dev Mode because when Super Dev Mode compiles the project, it seems to remove these files and the app fails because it can't find them.  

These values need to be configurable per project so that the includes can point to any location outside the main project where the GWT compiler blats them.

**Comment by slavap** [comment]
It's working in superdev mode, I'm using it on daily basis. Something in your project conflicts with GWT copy from public folder functionality. Give me more information about your project.

**Comment by slavap** [comment]
I can disable js and css injection and include all needed scripts manually in your index.html
Just add static constructor in your app entry point:
```java
public class EntryPointBase implements EntryPoint {

    static {
        if (/* your condition for manual scripts loading */) { 
            com.sksamuel.jqm4gwt.Resources.Loader.manualLoading = true;
            com.sksamuel.jqm4gwt.plugins.datatables.Resources.Loader.manualLoading = true;
            com.sksamuel.jqm4gwt.plugins.datebox.Resources.Loader.manualLoading = true;
        }
    }

```
