### ISSUE TITLE
Why not use fluent all the time?

### ISSUE THREAD

**Issue by MontyPan** [jqm4gwt/jqm4gwt#104]
For example, the setter of `JQMListItem`, these method are fluent:

* setAside()
* setCount()
* setId()
* setUrl()

these method are not: 

* setIcon()
* setImage()
* setThumbnail()
* setHref()

I am confused...... :confused:

**Comment by slavap** [comment]
:-) I'm using UiBinder all the time, so fluent is not important for me, that's why it's a little bit chaotic.

**Comment by MontyPan** [comment]
I like UiBinder, although GWT 3.0 could remote it... :scream:

But sometimes we still need create UI programmatically. Can I improve this part for official repo?

**Comment by slavap** [comment]
Sure. I'm planning new release as soon as GWT 2.8 released.

**Comment by MontyPan** [comment]
I forgot something about UiBinder...... :skull: 

```XML
<!-- It's OK -->
<list:JQMListItem href="#" />

<!-- Error: JQMListItem has no appropriate setUrl() method -->
<list:JQMListItem url="#" />
```

It seem UiBinder only bind standard setter which return type is void.
On the other hand, could we say `setUrl()` / `setAside()` ... is wrong?

If the answer is "YES", the API improvement will be:

1. Change the return type of `setAside()` from `JQMListItem` to void
1. Provide alternative method of `setAside()`、`setIcon()`, like `withAside()`、`withIcon()`

Any suggestion?

**Comment by slavap** [comment]
1. That's correct: "UiBinder only bind standard setter which return type is void".
    So setters should always return void.
2. For "reactive" programming corresponding withX() methods should be added.

**Comment by MontyPan** [comment]
OK, I will try to improve this part as I can...  (busy busy busy, need a vacation :sob: )
