### ISSUE TITLE
Popup scrolling issue with anodoid

### ISSUE THREAD

**Issue by mindoLife** [jqm4gwt/jqm4gwt#97]
i have a long content that is displayed inside a popup, in pc browser every thing is good, but when i open it with my mobile, i can't scroll, and content is un reachable. 
i didn't check it with iPhone. and i'm using 1.4.3 Final version.

**Comment by slavap** [comment]
Try to apply the following CSS to your content panel:
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch;

**Comment by mindoLife** [comment]
Sorry, not working. 
i added it to
.ui-content
{
	overflow-y: scroll;
	-webkit-overflow-scrolling: touch;
}

is that what you mean?

**Comment by slavap** [comment]
Try 1.4.5, may be it's 1.4.3 problem. You can add scroll to any panel, try to apply it to FlowPanel which holds your widgets.

**Comment by mindoLife** [comment]
No luck! 
i'm depressed :( 
i also updated to the latest jquery version.

**Comment by slavap** [comment]
Ok, I've checked my code base. No popup with scrolling, but I have many JMQDialog with scrolling, and it's working fine on Android and iOS. On panels with long content I have:
```css
  overflow-x: hidden;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
```

**Comment by mindoLife** [comment]
Is there any deference between jqmdialog and opening jqmpage as a dialog(
as i do?)

**Comment by slavap** [comment]
No, it's all the same, JQMDialog almost empty class.

**Comment by slavap** [comment]
Ok, try it that way, should be working:

```xml
<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">

<ui:UiBinder 
  xmlns:ui='urn:ui:com.google.gwt.uibinder'
  xmlns:g='urn:import:com.google.gwt.user.client.ui'
  xmlns:jqm='urn:import:com.sksamuel.jqm4gwt'
  xmlns:b="urn:import:com.sksamuel.jqm4gwt.button">
  
  <ui:style>
    .content {
      max-height: 500px;
      height: 500px;
    }
  </ui:style>
  
  <jqm:JQMDialog containerId="testDialog1" dlgTransparent="true" corners="false" 
    dlgCloseBtn="RIGHT" dlgCloseBtnText="Discard Dialog"
    contentAddStyleNames="jqm4gwt-scrollable-page-content {style.content}">
    <jqm:toolbar.JQMHeader text="Test Dialog 1 Header" />
    <g:FlowPanel addStyleNames="jqm4gwt-scrollable-main-stage">
      <jqm:html.Heading.H3 text="Some scrollable content could be placed here..."/>
      <b:JQMButton text="Button01" />
      <b:JQMButton text="Button02" />
      <b:JQMButton text="Button03" />
      <b:JQMButton text="Button04" />
      <b:JQMButton text="Button05" />
      <b:JQMButton text="Button06" />
      <b:JQMButton text="Button07" />
      <b:JQMButton text="Button08" />
      <b:JQMButton text="Button09" />
      <b:JQMButton text="Button10" />
      <b:JQMButton text="Button11" />
      <b:JQMButton text="Button12" />
      <b:JQMButton text="Button13" />
      <b:JQMButton text="Button14" />
      <b:JQMButton text="Button15" />
      <b:JQMButton text="Button16" />
      <b:JQMButton text="Button17" />
      <b:JQMButton text="Button18" />
      <b:JQMButton text="Button19" />
      <b:JQMButton text="Button20" />
    </g:FlowPanel>
  </jqm:JQMDialog>
</ui:UiBinder>
```

**Comment by mindoLife** [comment]
i'm sorry for bothering! i found the following line in a script that is
running, and it do all problems

document.addEventListener('touchmove', function (e) { e.preventDefault();
}, false);

JQM4GWT is perfect :)

**Comment by slavap** [comment]
My example is slightly different. It's limited height window with scrollable content inside. Glad you've resolved your problem.
