### ISSUE TITLE
Css not loading?

### ISSUE THREAD

**Issue by neridonk** [jqm4gwt/jqm4gwt#98]
when i load the files online it work:    
link type="text/css" rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
		    script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

but with my code in the entry point it doesnt, when  i look it Webdelevoper tool -> network i see the Files  but the style etc aren't applied to my elements

ScriptUtils.injectCss(true,"jquery.mobile-1.4.5.min.css");
		ScriptUtils.injectJs(true,new InjectCallback() {
			
			@Override
			public void onSuccess(Collection<String> result) {
					
				ScriptUtils.injectJs(true,new InjectCallback() {
					
					@Override
					public void onSuccess(Collection<String> result) {
							
						ScriptUtils.waitJqmLoaded(new Callback<Void, Void>() {
							
							@Override
							public void onSuccess(Void result) {
								IntroPage page = new IntroPage();
								JQMContext.changePage(page);								
							}
							
							@Override
							public void onFailure(Void reason) {
								
							}
						});			
						
					}
				}, "jquery.mobile-1.4.5.min.js");
				
				
			}
		}, "jquery-1.9.1.min.js");

**Comment by slavap** [comment]
Never tried to inject them that way. Instead of http://code.jquery.com/... you can use "local" relative path in your html:
```html
<script src="js/jquery.mobile-1.4.5.min.js"></script>
```

**Comment by neridonk** [comment]
the local relative path doesn't work either, but this worked for me :dancer: 


private void scriptInject()
	{

                                                                DivElement div = Document.get().createDivElement();
								div.setAttribute("data-role", "page");
								div.setId("start");
								RootPanel.get().getElement().appendChild(div);
								GlobaleVariablen.setLicence(result);

								loadCss("jquery.mobile-1.4.5.min.css");
								scriptInject();


		ScriptInjector.fromUrl("jquery-1.9.1.min.js").setCallback(new Callback<Void, Exception>()
		{
			public void onFailure(Exception reason)
			{
				Window.alert(Webportal.constants.fehler());
			}

			public void onSuccess(Void result)
			{
				ScriptInjector.fromUrl("jquery.mobile-1.4.5.min.js").setCallback(new Callback<Void, Exception>()
				{
					public void onFailure(Exception reason)
					{
						Window.alert(Webportal.constants.fehler());
					}

					public void onSuccess(Void result)
					{
						GlobaleVariablen.setMobileAnsicht(true);
						new MobileEntryPoint();
					}
				}).setRemoveTag(false).setWindow(ScriptInjector.TOP_WINDOW).inject();

			}
		}).setRemoveTag(false).setWindow(ScriptInjector.TOP_WINDOW).inject();

	}
	private native void loadCss(String url)/*-{
					var fileref=document.createElement("link");
				          fileref.setAttribute("rel","stylesheet");
					fileref.setAttribute("type","text/css");
				         fileref.setAttribute("href",url);
				       $doc.getElementsByTagName("head")[0].appendChild(fileref);
													}-*/;

**Comment by slavap** [comment]
That's really strange. I have index.html and jquery js files in src/main/webapp folder, and can inject them with relative path without any problem.
