### ISSUE TITLE
JQMSelect refresh callback

### ISSUE THREAD

**Issue by neridonk** [jqm4gwt/jqm4gwt#99]
Hey, im trying to dynamicly add new content to the JQM selection panel, but if i do this my panel is shown wrong (small) and no close button i guess not right rendered, when i close the dialog and reopen it is displayed right, how can i fix this: 

	
		selectionpanel.addTapHandler(new TapHandler()
		{

			@Override
			public void onTap(TapEvent event)
			{
				

				presenter.load(null, new Callback()
				{

					@Override
					public void onUnavailable()
					{
					}

					@Override
					public void onSuccess()
					{
						selectionpanel.refresh();
						offeneAntraege.open();
							
						});

					}
				});

			}
		});

**Comment by slavap** [comment]
It's non-native (native="false") JQMSelect, right? How do you add new items? 
The following way is working, see examples:
select.addOption(opt);
select.refresh();

Also in your case JQMContext.render(select.getParent().getElement()) may help.

**Comment by neridonk** [comment]
I have to say that it is a JQMFilterable , i tryed 

selectionpanel.addTapHandler(new TapHandler()
    {

        @Override
        public void onTap(TapEvent event)
        {


            presenter.load(null, new Callback()
            {

                @Override
                public void onUnavailable()
                {
                }

                @Override
                public void onSuccess()
                {
                    selectionpanel.refresh();
                    offeneAntraege.open();
                   JQMContext.render(select.getParent().getElement())

                    });

                }
            });

        }
    });


and also in the load methode a refresh after an addOption 

select.addOption(opt);
select.refresh();


i think the problem is that, when i tap on the selection Dialog will open before the items are added or idk :rabbit:

**Comment by slavap** [comment]
Show me simplified, but complete version of your code. Then I'll probably find out how to help you.

**Comment by neridonk** [comment]
selectionpanel.addTapHandler(new TapHandler()
{

    @Override
    public void onTap(TapEvent event)
    {


        presenter.load(list, new Callback()
        {

            @Override
            public void onUnavailable()
            {
            }

            @Override
            public void onSuccess()
            {
                selectionpanel.refresh();
                offeneAntraege.open();
               JQMContext.render(select.getParent().getElement())

                });

            }
        });

    }
});


	public void load(List<data> suggestList , final Callback callback)
	{
		selectionpanel.clear();
		for (data data : suggestList)
		{
			this.addOption(data.name);
			this.refresh();
		}

               callback.onSuccess();

	}

**Comment by neridonk** [comment]
Ok i solved it this morning :+1:  thank you for ur help it pointed me to the right direction
